### PR TITLE
Docs round2

### PR DESCRIPTION
**Pull request by zfisch**
@amycoffin please take a look and let me know if this looks correct to you! It has a couple changes you made on March 7th `Made a change per 3/7 Mandy email`

### CODE REVIEW

**Comment by zfisch** [comment]
you can also review it at http://104.210.44.242:8080/faq if that's easier -- i updated it with the latest changes

**Comment by amycoffin** [comment]
Looks good! The only thing that I see missing is [this ticket](https://github.com/BRCAChallenge/brca-exchange/issues/744), which is ready

Apologies for the multiple points of contact!

**Comment by zfisch** [comment]
@amycoffin it seems that `update Berghofer Medical research institute to read "QIMR Berghofer Medical Research Institute"` has already been done (I couldn't find only "Berghofer Medical research institute" anywhere on the facts and stats page).

If you do see that it still needs an update, could you share a screenshot of where the change needs to take place?

**Comment by zfisch** [comment]
@amycoffin gave me the ok to merge this PR

**Pull request merged**
