### PR TITLE
utf encoding fix for literature searching code, closes #542

### LINKED ISSUE #542: make sure fix to ga4gh api for audrey is working

### PR DESCRIPTION
**Pull request by zfisch**

### CODE REVIEW

**Comment by zfisch** [comment]
@almussel could you confirm that this fixes the issue you were running into before merge?

It should work to pull this branch and reference your local code when running the literature search.

**Comment by almussel** [comment]
@zfisch Sorry for the slow response -- I can take a look at this tonight.

**Comment by almussel** [comment]
@zfisch I pulled the branch and tried to follow the instructions to spin up a local server, but I ran into some issues with installing postgres, etc. Can you spin up a provisional instance for me to test my code with?

**Comment by zfisch** [comment]
Hey! I just set up the code on my dev server. Try hitting this url for the backend instead of brcaexchange.org: `http://brcaexchange-dev.cloudapp.net:9004`.

**Pull request merged**
